version: '3'

services:
  db:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
  shortener:
    build: ./
    command: /app/main
    depends_on: 
      - db
    networks:
      - default
    ports:
      - "8080:8080"
