// Code generated by MockGen. DO NOT EDIT.
// Source: urlsdelete.go

// Package mock_urlsdelete is a generated GoMock package.
package mock_urlsdelete

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockURLDeleter is a mock of URLDeleter interface.
type MockURLDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockURLDeleterMockRecorder
}

// MockURLDeleterMockRecorder is the mock recorder for MockURLDeleter.
type MockURLDeleterMockRecorder struct {
	mock *MockURLDeleter
}

// NewMockURLDeleter creates a new mock instance.
func NewMockURLDeleter(ctrl *gomock.Controller) *MockURLDeleter {
	mock := &MockURLDeleter{ctrl: ctrl}
	mock.recorder = &MockURLDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLDeleter) EXPECT() *MockURLDeleterMockRecorder {
	return m.recorder
}

// SetDeleteFlag mocks base method.
func (m *MockURLDeleter) SetDeleteFlag(IDs []string, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDeleteFlag", IDs, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDeleteFlag indicates an expected call of SetDeleteFlag.
func (mr *MockURLDeleterMockRecorder) SetDeleteFlag(IDs, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeleteFlag", reflect.TypeOf((*MockURLDeleter)(nil).SetDeleteFlag), IDs, userID)
}
